### ISSUE TITLE
Images or PDF not works

### ISSUE THREAD

**Issue by Paul75** [Marcelh1983/angular-document-viewer#1]
Hello,

I test to open images or PDF and not works. I use google to show but errors appear....

Thanks

**Comment by Marcelh1983** [comment]
Hi Paul,

Images are not supported. Pdf should work, see here: https://stackblitz.com/edit/angular-dx1vfj. 
If you do something similiar and it doesm't work; could you provide a plunkr/stackblitz to reproduce?

Thanks!
