### ISSUE TITLE
Unable to open .mov format

### ISSUE THREAD

**Issue by grishabh1992** [Marcelh1983/angular-document-viewer#11]
Unable to open .mov format.

I download the project and I added one more format in option (.mov) and url(https://cl.ly/3X3N361x2h1V/Screen%20Recording%202017-02-06%20at%2002.53%20PM.mov').

I am attaching the screenshot of the same
![image](https://user-images.githubusercontent.com/13380923/68022198-a4802b80-fcc9-11e9-9c69-0ba086aeb520.png)

**Comment by Marcelh1983** [comment]
Thanks @grishabh1992 for reporting. I removed the video files from the supported formats.
