### ISSUE TITLE
Offline 

### ISSUE THREAD

**Issue by whitegoat** [Marcelh1983/angular-document-viewer#12]
Hi Marcelh,

Is this working **offline**?, example if i dont have internet connection at some point?
Currently i need to check the offline version also. 

Thanks & Regards,
SK

**Comment by Marcelh1983** [comment]
The document are sent to the google or office viewer. You have be online for that. This cannot be changed

**Comment by Marcelh1983** [comment]
Hi @whitegoat `npm i ngx-doc-viewer@next` will have the mammoth viewer. Which converts docx to html locally.
Also add mammoth: 
```sh
npm install mammoth --save
```
and make sure mammoth.browser.min.js is loaded. For the angular/cli you would add the following in angular.json:

```json
    "scripts": [
        "node_modules/mammoth/mammoth.browser.min.js"
    ]
```
See the demo site in local-files branch for example code.
