### ISSUE TITLE
Shows the script but not the file

### ISSUE THREAD

**Issue by sevriugin** [Marcelh1983/angular-document-viewer#13]
In my case the component shows the script not the file. Test it also in demo the same result. The the file link  [here](https://drive.google.com/file/d/1ZLzxeQ0rLLHl8afqR734Di9jWlCZbJY7/view)

**Comment by Marcelh1983** [comment]
This link you sent is already a word document in the google viewer. If you want to show that in you app you can convert your url to a safeUrl and show this link in an iframe. Just like I do in document-viewer.component.ts
