### ISSUE TITLE
Issue in Office Viewer

### ISSUE THREAD

**Issue by shubhpaliwal** [Marcelh1983/angular-document-viewer#14]
I am trying to use the 'office view' instead of 'google doc'.
But the issue is it is showing data from cache maybe, because when I even deleted the file from the storage, then also it is showing the file.
The google view is showing a correct error message when the file is not present but the office view does not show any message and shows me the old file.

**Comment by Marcelh1983** [comment]
Hi @shubhpaliwal could be that office caches your document. There's no way to control how the office viewer works. The only thing the library could do is check if the file exists first, but I think that's in most cases an unnecessary check, so if you would like to have this check, you should do it in your own app.

**Comment by shubhpaliwal** [comment]
Hi, @Marcelh1983 thanks for a quick reply.
The problem I am having is that the file is on Microsoft Blob Storage and when I use my application it creates a new file on that storage and I am passing the new file link as the URL, so I am not sure how it is making a cache. The file is getting updated every time and google doc viewer is showing it perfectly but the office viewer shows the version that doesn't even exist.
