### ISSUE TITLE
Is there a way to test if a viewer type works?

### ISSUE THREAD

**Issue by SGissubel** [Marcelh1983/angular-document-viewer#18]
In the application I am working on - I am sometimes unsure what type of document will be used/viewed. I want to be able to catch the following BEFORE it displays: 
![image](https://user-images.githubusercontent.com/21371158/71127387-07b21880-21b9-11ea-8a33-f922551f41b8.png)

I tried a regular try/catch - this didn't work.  I noticed that when I used 'office' - it gave me this page - but when I hard-coded 'google' it worked in this case. But these files are being saved in many different ways - so I want to be able to see if it works, if not - catch it & set it to the other viewer type. 

Generally - I want to catch that error: `The URL of the original file is not valid .... ` and then switch the viewer. OR - make a custom display if the link does not work. 

Thanks!

**Comment by Marcelh1983** [comment]
Hi @SGissubel, I don't think you can do what you want. This library just sends the url to or the Google or the office viewer and loads it in an iframe. Because you can't access the contents of an iFrame because cross-domain I don't think you can determine the error in the iframe
