### ISSUE TITLE
"reloading.." is stopping my other iframe as well

### ISSUE THREAD

**Issue by SilinaGeorge** [Marcelh1983/angular-document-viewer#19]
I have a spotify widget iframe that is playing music. Whenever "reloading..." is console logged from doc-viewer my spotify widget iframe stops playing music, looks like your code is reloading every iframe that has "src" as an input, your help is appreciated. I commented out everywhere where it said `iframe.src = iframe.src;` in your code and my music didnt stop

here is my doc viewer:
` <ngx-doc-viewer [url]="url" viewer="google" style="width:100%;height:87vh;"></ngx-doc-viewer>`

here is my spotify :
`  <iframe [src]="srcUrl" width="100%" height="300px" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>`

**Comment by Marcelh1983** [comment]
Hi @SilinaGeorge, i added an option to check the content loaded check for the google viewer. Please upgrade to 0.1.25 and add: `<ngx-doc-viewer [googleCheckContentLoaded]="false"` let me know if it fixes your problem.

**Comment by SilinaGeorge** [comment]
hi @Marcelh1983 Its working in dev, however when I try to build it in prod with `ng build --configuration=production` its giving me the following:
![image](https://user-images.githubusercontent.com/19698115/71429530-025f3d00-2695-11ea-8397-23e48e4ae893.png)

**Comment by Marcelh1983** [comment]
Upgrading angular and cli to the latest version solves this problem. Has probably something to do with the version that of angular-devkit/build-angular see also issue #15 there are a lot of libraries that have this issue. Unfortunately I have not found a solution to support older version and newer
