### ISSUE TITLE
PDF Documents not working with office viewer.

### ISSUE THREAD

**Issue by enagaraj89** [Marcelh1983/angular-document-viewer#2]
I am able to view PDF and Word documents using google document viewer, but same pdf document I am not able to view with office viewer. Office viewer is displaying only word documents. Is this a known limitation of office viewer or Is there a code/configuration change to make PDF documents view-able with office viewer.

**Comment by Marcelh1983** [comment]
Hi @enagaraj89. Thanks for pointing out pdf is not supported in the office viewer. The office viewer only supports 'office' types. I added a filetype support section in the readme.
