### ISSUE TITLE
Can't Open blob object in html iframe

### ISSUE THREAD

**Issue by sagaraher** [Marcelh1983/angular-document-viewer#22]
Hi Team ,
I am struggling with blob object integration with this plugin .
I can open blob object .xlsx .ppt .doc file in this plugin .

**Comment by sagaraher** [comment]
Hi Team ,
 I am struggling with blob object integration with this plugin .
 I can't open or view blob object from .xlsx .ppt .doc file in html by using this plugin .

**Comment by Marcelh1983** [comment]
Hi @sagaraher , because the library uses the online google or office viewer the url needs to be available publicly. I'm working on solution to be able to view documents that are only available locally, but that preview will have some limitations. I hope I can publish a beta version today.

**Comment by Marcelh1983** [comment]
Hi @sagaraher `npm i ngx-doc-viewer@next` will have the mammoth viewer.

Also add mammoth: 
```sh
npm install mammoth --save
```
and make sure mammoth.browser.min.js is loaded. For the angular/cli you would add the following in angular.json:

```json
    "scripts": [
        "node_modules/mammoth/mammoth.browser.min.js"
    ]
```
See the demo site in local-files branch for example code.

Please let me know if this is useful for you.
