### ISSUE TITLE
not able to view any document in google/ office - after updating to latest version 

### ISSUE THREAD

**Issue by leelaakula** [Marcelh1983/angular-document-viewer#24]
Hi @Marcelh1983 

After that latest change to 1.0.0,
Below is the directive I am using in my template.
**<ngx-doc-viewer [url]="tempUrl" viewer="office" style="width:100%;height:93%;"></ngx-doc-viewer>**

After inspecting, we are **not able to render** anything in DOM.
![image](https://user-images.githubusercontent.com/38076999/72237077-46dc5980-35ff-11ea-86e9-0154b73374c8.png)

In view, Nothing gets loaded.

Am i missing something  or **property to show content logic** need to check.

Thank you in advance,
Anuroop

**Comment by Marcelh1983** [comment]
Hi Anuroop,

I'm not sure what goes wrong. Are you sure your tempUrl has a value?
I created a stackblitz with version 1.0.0 that works.

Could you see if you could change my stackblitz and reproduce your problem?

https://stackblitz.com/edit/ngx-doc-viewer-example

**Comment by leelaakula** [comment]
Hi @Marcelh1983 

My component logic messed up. Your code is perfect, my mistake, sorry, just one CSS styling fix needs to be done.

![image](https://user-images.githubusercontent.com/38076999/72273324-2ab4d880-3650-11ea-81a1-2c6ff6be0f96.png)
 
Thanks again 
Anuroop
