### ISSUE TITLE
does not render in ionic cordova

### ISSUE THREAD

**Issue by nhhockeyplayer** [Marcelh1983/angular-document-viewer#26]
does not render in ionic cordova

iOS renders but no scrolling or library features for pdf just first page

Android renders blank white page for pdf

**Comment by Marcelh1983** [comment]
Hi @nhhockeyplayer ,

I use the embed tag to display the pdf. It depends on the browser how it's rendered.
If you want to be sure that local pdf file are shown correctly on each browser then I would recommend using pdf.js: https://www.npmjs.com/package/ng2-pdfjs-viewer. I will update the readme with more info about pdf rendering.

**Comment by nhhockeyplayer** [comment]
thanks marcel for your speedy response

yeah i peeked at your source code and saw the embed tag being used and tried to search web for ay hints

be nice if you could find a wokraorund

i like your code

nice job

**Comment by nhhockeyplayer** [comment]
attempted sanitizing the url without remedy

**Comment by nhhockeyplayer** [comment]
https://stackoverflow.com/questions/39393431/how-with-angular2-rc-6-disable-sanitize-on-embed-html-tag-which-display-pdf/39394814#39394814

appears to be bug in chrome for embed

im trying to come up with workaorund

**Comment by nhhockeyplayer** [comment]
ok this looks like the patch fo library

its too involved for me now dont have time tot ake apart your library

and will go with other lbrary menituoned

unless you want to patch this and post new release I will go with yours

cheers

Ken

https://next.plnkr.co/edit/CmolRdrrzY9LbOij39l7?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview

**Comment by nhhockeyplayer** [comment]
well I struck out... looked everywhere and cannot find a pdf viewer that functions in ionic

if you fixed this yours would be the ONLY one that does this

its a mess not one out there follows thru and there is at least half a doz viewers

anything deep in cordova or ionic only permits pushing a button... nothing embedded in an angular template

be nice to see you take it to max I will be first user

**Comment by Marcelh1983** [comment]
I'm not planning to do a lot of effort to support cordova or ionic in this library. Think this become more stackoverflow question right now :) 

I haven't used ionic but did create a cordova app. You can check whether your app is running in cordova and call a cordova plugin right? Maybe you could call something like this: https://github.com/sitewaerts/cordova-plugin-document-viewer. 

Did you try pdf.js? Didn't that work?

**Comment by nhhockeyplayer** [comment]
thanks, your viewer works great for web
