### ISSUE TITLE
Document viewer not working for .xlsx file.

### ISSUE THREAD

**Issue by vikash09** [Marcelh1983/angular-document-viewer#3]
I am using 
`    "ngx-doc-viewer": "^0.1.20",`

In documentation

office viewer
> .ppt, .pptx, .doc, .docx, .xls and .xlsx

`<ngx-doc-viewer *ngIf="dataUrl" [url]="dataUrl" viewer="office" style="width:100%;height:100%;"></ngx-doc-viewer>`

it says that it's supporting the above files types. but for .xlsx it's not working, as shown in below image

![image](https://user-images.githubusercontent.com/21213817/59515477-cfb1dc00-8edc-11e9-92f4-7d363f91bb09.png)

For the docx file it's working awesome.

Please help me to find out this issue.

**Comment by vikash09** [comment]
The problem was in file it's generated by code and the file get invalid some how but I still can access it in the office.

**Comment by Marcelh1983** [comment]
Good to hear you found the problem and you find this package useful.
