### ISSUE TITLE
Prod build fails (using ngx-doc-viewer@1.0.0)

### ISSUE THREAD

**Issue by nvkolluru** [Marcelh1983/angular-document-viewer#31]
ERROR in ./node_modules/ngx-doc-viewer/fesm5/ngx-doc-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

**Comment by Marcelh1983** [comment]
Hi @nvkolluru  see #10 updating the cli: ng upgrade @angular/cli (and also @angular-devkit/build-angular) solves this problem. If this is not an option for your project then use version 0.1.19.
