### ISSUE TITLE
Compile Errors when using Angular 8 and Ivy

### ISSUE THREAD

**Issue by ingeJulianLasso** [Marcelh1983/angular-document-viewer#34]
```
ERROR in No suitable injection token for parameter 'domSanitizer' of class 'NgxDocViewerComponent'.
no type or decorator
```
```
Angular CLI: 8.3.19
Node: 12.14.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/material                 8.2.3
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```
ivy and aot builds enabled.

**Comment by Marcelh1983** [comment]
Hi @ingeJulianLasso .

I'm not sure what causes the problem. I'm not experiencing this issue with angular 9. There are some other issues on github that report about this problem https://github.com/KillerCodeMonkey/ngx-quill/issues/614 something to do with compile target? If there is something I could do to fix this problem and you can point me in the right direction,let me know.

**Comment by ingeJulianLasso** [comment]
Hello @Marcelh1983 

Thanks for answering, what I mean is that when I try to compile in Angle 8 using Ivy I get the following error.

```
ERROR in No suitable injection token for parameter 'domSanitizer' of class 'NgxDocViewerComponent'.
no type or decorator
```

This error is indicated in the library I use to display PDF and Office files online.

I would like to know if there is any way to fix it, I have already consulted and tried many solutions but I always get the same error.

**Comment by ingeJulianLasso** [comment]
I updated my project to Angular 9 and the errors disappeared. Thank you
