### ISSUE TITLE
ERROR in node_modules/ngx-doc-viewer/document-viewer.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by senthil-developer** [Marcelh1983/angular-document-viewer#36]
I'm facing this issue while compiling my Angular Project. And I'm using the version of ngx-doc-viewer": "^1.0.1".
![Error123](https://user-images.githubusercontent.com/50570744/75041621-f0f2af80-54e2-11ea-9b2f-a030d287de4c.png)

My Project - package.json:
{
  "name": "Sample-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@nguniversal/express-engine": "^8.2.6",
    "angular-datatables": "^8.0.0",
    "angular2-jwt": "^0.2.3",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.9.3",
    "datatables.net": "^1.10.20",
    "datatables.net-dt": "^1.10.20",
    "jquery": "^3.4.1",
    "mdbootstrap": "^4.10.1",
    "ng-angular8-datatable": "^0.9.11",
    "ngx-cookie": "^4.1.2",
    "ngx-doc-viewer": "^1.0.1",
    "ngx-toastr": "^11.2.1",
    "popper.js": "^1.16.0",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.0-rc.2",
    "rxjs": "~6.4.0",
    "save": "^2.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular/cli": "~8.3.19",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/datatables.net": "^1.10.18",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by jescobar13** [comment]
I have the same problem...

**Comment by Marcelh1983** [comment]
Hi @jescobar13  and @senthil-developer, thanks for reporting this issue. I'm investigation the problem. Think upgrading typescript to 3.6 will fix this issue, but I'll check if I can support 3.5 as well

**Comment by Marcelh1983** [comment]
@jescobar13 and @senthil-developer , 1.0.2 should solve this.

**Comment by senthil-developer** [comment]
@Marcelh1983 Thanks for your response and fix. After your fix, I've updated the ngx-doc-viewer to 1.0.3,  then I compiled it once again it's working fine there is no build error. Thanks for your great work.
