### ISSUE TITLE
ngOnChanges  - isFirstChange on undefined

### ISSUE THREAD

**Issue by pmelisko** [Marcelh1983/angular-document-viewer#37]
Hi,

first of all, thanks for great job. There is a small bug in this condition.

https://github.com/Marcelh1983/angular-document-viewer/blob/master/modules/document-viewer.component.ts#L71

changes&& (changes.**viewer.isFirstChange** ... -> viewer can be undefined

I changed url, and my change object just { url: ...}, so it fails on accessing property isFirstChange on viewer, because viewer is undefined. That condition should check existance of viewer on change object:

`changes.viewer && (changes.viewer.isFirstChange || changes.viewer.currentValue !== changes.viewer.previousValue)`

**Comment by Marcelh1983** [comment]
Thanks @pmelisko , and sorry for the bug. should be fixed in 1.0.3
