### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by avoThomas** [Marcelh1983/angular-document-viewer#38]
I have a multilingual app, is there no way to be able to translate the messages like "No Preview Available"?

**Comment by Marcelh1983** [comment]
Hi @avoThomas, this might work with queryParams to add a language. I'll have a look at it today.

**Comment by Marcelh1983** [comment]
Hi @avoThomas you can now pass query params in 1.0.4. To set the google viewer in Dutch for example you should use: <ngx-doc-viewer queryParams="hl=Nl"

**Comment by avoThomas** [comment]
Excellent, thank you.

**Comment by avoThomas** [comment]
Do you know when the 1.0.4 version will be releasd?

**Comment by Marcelh1983** [comment]
I'm sorry, I  was in the understanding I already published the new version, but I must have forgotten. It's published now :)
