### ISSUE TITLE
I want to disable the right click options in ngx-doc-viewer.

### ISSUE THREAD

**Issue by Prasanth-FrontendDeveloper** [Marcelh1983/angular-document-viewer#39]
I'm using this module only for viewing my documents it should not allow the user to copy the content or saving the document so this needs to be restricted.

**Note:** This is **highest priority** for my project. Also I've used **Javascript method "oncontextmenu"** it was working everywhere in all **HTML** elements but it was not accepting to this module. Please allow this Javascript method "oncontextmenu" to this module or suggest me something else.

**Comment by Marcelh1983** [comment]
Hi @Prasanth-FrontendDeveloper ,

You can try to use: <ngx-doc-viewer disableContent="all"

It renders an overlay on top of the iframe with the document, which prevents copying.

**Comment by Prasanth-FrontendDeveloper** [comment]
Yes @Marcelh1983 Even if I used the **disableContent="all"**, it's not allowing the user to **scroll the document and zoom** options. I just want to allow the user to view the documents, the user able to scroll and zoom options but need to **disable the right click** because of user can save the documents.

**Note**: Also I have used the **input disableContent=" popout-hide ".** Because the user can't able to **download the documents** so I used the popout-hide option. Please suggest me something else, it will be more helpful for me.

**Comment by Marcelh1983** [comment]
Hi @Prasanth-FrontendDeveloper, first of all, if the document is publicly available you just make it a bit harder for the user to download the document, but they still can. Problem with the document viewer is that's its loaded in an iframe where you can't intercept the right click. Only option they I can think of is the overlay option which as you pointed out has other disadvantages. Maybe there is another way I didn't think of. I would suggest to clone this repository and use the demo app to try to make something that meets you requirements. If you succeed I can merge the change and publish a new version. For now I'm closing this issue

**Comment by Prasanth-FrontendDeveloper** [comment]
Okay, @Marcelh1983 I will check and try to fix this issue. If it's fixed I will let you know about the fix. Thanks for your quick response.

**Comment by PRUTHIRAJ97** [comment]
I am using this module for document view only but the user should not copy the file or right-click on the file, In the right-click the save file and copy option should be disabled. Is there any new version of this tool available?

**Comment by dee2499** [comment]
Hi @Marcelh1983 and other members. 
I want to hide/remove the menu option (download and print to pdf) and open in new window.

![image](https://user-images.githubusercontent.com/15178407/139798303-149c7b1e-5962-40df-afb6-77c22e667d51.png)

If anyone has any idea please help. 
Thanks you,

**Comment by Pruthi-raj** [comment]
@dee2499 ,can you please tell me which pdf viewer you are using ?

**Comment by dee2499** [comment]
i am using ngx-doc-viewer for ppt display. @Pruthi-raj

**Comment by dee2499** [comment]
Hello. 
If anyone has idea about load complete event or something. I want an event when ppt file loads complete.
