### ISSUE TITLE
Document viewer is not working for images with google viewer

### ISSUE THREAD

**Issue by ramya0311** [Marcelh1983/angular-document-viewer#4]
In the official demo provided, .png files are not working

**Comment by Marcelh1983** [comment]
Hi @ramya0311,
Thanks for pointing out. Seems like the source I found with supported types wasn't correct. png and jpg are not supported, see also this [thread](https://stackoverflow.com/questions/24325363/google-doc-viewer-which-formats-are-really-supported). I updated the readme and the demo.
