### ISSUE TITLE
Google viewer reload multiple times before documents (iframe) loads

### ISSUE THREAD

**Issue by davidnjuko** [Marcelh1983/angular-document-viewer#41]
I can see in the console, I have error messages about script dynamics put I'm stuck with this

![Screenshot 2020-03-27 at 11 35 37](https://user-images.githubusercontent.com/2836227/77747557-2d07bb80-701f-11ea-8b4a-d825be3b9c4a.png)

After several attempt the document finally loads but it takes forever before getting the preview for the app user

![Screenshot 2020-03-27 at 11 33 31](https://user-images.githubusercontent.com/2836227/77747464-077ab200-701f-11ea-9db3-8f8ec37d1700.png)

Any idea ?

**Comment by Prasanth-FrontendDeveloper** [comment]
Even I too facing the same problem. If I use 'google' viewer this issue occurs, the document reloads up to 4-5 times then only the user can see the document. Please try to fix it @Marcelh1983  it will be more useful for my project.

**Comment by Marcelh1983** [comment]
@Prasanth-FrontendDeveloper you can disable reloading by setting [googleCheckContentLoaded]="false" but you might have [this](https://stackoverflow.com/questions/40414039/google-docs-viewer-returning-204-responses-no-longer-working-alternatives) problem. If you do need the reload check you can also try to use another interval [googleCheckInterval] (default 3000). The issue of @davidnjuko seems to be different.

**Comment by Marcelh1983** [comment]
if the document loads eventually it should be able to solve with the [googleCheckContentLoaded]="false" or a higher interval e.g. [googleCheckInterval]="10000"
