### ISSUE TITLE
issue to display a google document URL or a document in dropbox URL

### ISSUE THREAD

**Issue by Zedat** [Marcelh1983/angular-document-viewer#43]
Hello, 
I am trying to display with the docment-viewer a document URL that is stored in the google drive or dropbox.
For example for google drive: https://docs.google.com/document/d/1kxoN1T0dAKl9qLmpMEOu_R-XHnuvQGwjiddAtdQm98M/edit?usp=sharing

for dropbox the document is: https://www.dropbox.com/scl/fi/9f5keih4ou4wyox03u2ar/wording.docx?cloud_editor=word&dl=0&ignore_lock=1&rlkey=vvtnjcalosgt6vq114mpgv47d

what I am getting is the metadata of the document. ( see below ) 
does doc-viewer support google URL or other URL where the document is stored?

Thanks, 
Ben 

a part of the output : (
<!DOCTYPE html><html xml:lang="en" class="maestro" xmlns="http://www.w4.org/1999/xhtml"><head><script nonce="bw1ySHpIxqVKLQlqfzno">
window._goch_ = {};
window.addEventListener('click', function(event) {
    'use strict';
    for (var elm = event.target; elm; elm = elm.parentElement) {
        if (elm.id &&
            window._goch_.hasOwnProperty(elm.id) &&
            window._goch_[elm.id].call(elm, event) === false) {
            event.preventDefault();
        }
    }
}, true);
window._csp_external_script_nonce = "I8aYaRO8Ewe9iqCewVEu"</script><link href="uc6bda96a6fd834d572c43ed5c90.previews.dropboxusercontent.com" rel="dns-prefetch" /><link href="https://cfl.dropboxstatic.com/static/images/favicon-vflUeLeeY.ico" rel="shortcut icon" /><script type="text/javascript" nonce="bw1ySHpIxqVKLQlqfzno">window.ST=+new Date();</script><link href="https://cfl.dropboxstatic.com/static/images/logo_catalog/dropbox_webclip_60_m1.png" rel="apple-touch-icon" /><link href="https://cfl.dropboxstatic.com/static/images/logo_catalog/dropbox_webclip_76_m1.png" rel="apple-touch-icon" sizes="76x76" /><link href="https://cfl.dropboxstatic.com/static/images/logo_catalog/dropbox_webclip_120_m1.png" rel="apple-touch-icon" sizes="120x120" /><link href="https://cfl.dropboxstatic.com/static/images/logo_catalog/dropbox_webclip_152_m1.png" rel="apple-touch-icon" sizes="152x152" /><meta content="text/html; charset=UTF-8" http-equiv="content-type" /><meta content="https://www.dropbox.com/scl/fi/9f5keih4ou4wyox03u2ar/wording.docx?cloud_editor=word&amp;dl=0&amp;ignore_lock=1&amp;rlkey=vvtnjcalosgt6vq114mpgv47d" property="og:url" /><meta content="Dropbox" property="og:site_name" /><meta content="website" property="og:type" /><meta content="Shared with Dropbox" property="og:description" /><meta content="160" property="og:image:width" /><meta content="wording.docx" property="og:title" /><meta content="210019893730" property="fb:app_id" /><meta content="https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-docx-large.png" property="og:image" /><meta content="160" property="og:image:height" /><meta content="summary" name="twitter:card" /><meta content="@Dropbox" name="twitter:site" /><meta content="https://www.dropbox.com/scl/fi/9f5keih4ou4wyox03u2ar/wording.docx?cloud_editor=word&amp;dl=0&amp;ignore_lock=1&amp;rlkey=vvtnjcalosgt6vq114mpgv47d" name="twitter:url" /><meta content="wording.docx" name="twitter:title" /><meta content="Shared with Dropbox" name="twitter:description" /><meta content="https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-docx-large.png" name="twitter:image" /><meta content="TnuSyOnBMNmtugbpL1ZvW2PbSF9LKvoTzrvOGS9h-b0" name="google-site-verification" /><meta content="EZKIczQcM1-DVUMz8heu1dIhNtxNbLqbaA9-HbOnCQ4" name="google-site-verification" /><meta content="tz8iotmk-pkhui406y41y5bfmfxdwmaa4a-yc0hm6r0fga7s6j0j27qmgqkmc7oovihzghbzhbdjk-uiyrz438nxsjdbj3fggwgl8oq2nf4ko8gi7j4z7t78kegbidl4" name="norton-safeweb-site-verification" /><meta content="https://cfl.dropboxstatic.com/static/images/logo_catalog/logo_m1.png" name="msapplication-TileImage" /><meta content="#ffffff" name="msapplication-TileColor" /><meta content="Dropbox is a free service that lets you bring your photos, docs, and videos anywhere and share them easily. Never email yourself a file again!" name="description" /><title>Dropbox - wording.docx</title><style type="text/css">.hny-skn { display: none; }</style><link href="https://cfl.dropboxstatic.com/static/images/favicon-vflUeLeeY.ico" rel="shortcut icon" /><script type="text/javascript" nonce="bw1ySHpIxqVKLQlqfzno">
    (function streamPreviewImg()

**Comment by Marcelh1983** [comment]
I added an option for other external viewer in 1.1.0
If you publish your document in google docs and use the url in ngxDocViewer

I haven't looked into dropbox but something similar might work for a dropbox file.
Let me know if works or you need any more help.

```html
    <ngx-doc-viewer
        [url]="http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh"
        viewer="url">
    </ngx-doc-viewer>
```
