### ISSUE TITLE
How to style div inside ngx-doc-viewer? 

### ISSUE THREAD

**Issue by AleksandarMiha** [Marcelh1983/angular-document-viewer#46]
sd

**Comment by AleksandarMiha** [comment]
@Marcelh1983

**Comment by suhailk4** [comment]
can you please elaborate what you are trying to achieve by styling something inside ngx-doc-viewer ?

**Comment by AleksandarMiha** [comment]
@suhailk4  I need to style div inside ngx-doc-viewer.
I am now created that div.. probably plugin is create...
I am import plugin and when I inspect inside plugin I see div and inside div p tag and table. 
I need only to change div tag. to centre text without to set text-align: centre direct on plugin.  @Marcelh1983

**Comment by Marcelh1983** [comment]
Hi @AleksandarMiha ,

In the demo project I did a test: adding class="test" and copy the scss in styles.scss and the background turned red. Doesn't that work in your code?

**Comment by AleksandarMiha** [comment]
Friend i need to style div inside  ngx-doc-viewer tag..

**Comment by AleksandarMiha** [comment]
@Marcelh1983

**Comment by AleksandarMiha** [comment]
Check this image. Div inside ngx tag  https://ibb.co/D57Bkqf
