### ISSUE TITLE
How to hightlight text in ngx-doc-viewer ? Using pipe or whatever ?

### ISSUE THREAD

**Issue by AleksandarMiha** [Marcelh1983/angular-document-viewer#48]
Hi,
I need to highlight text with input search. I want to search text inside ngx-doc-viewer and don't know how to do it? It is impossible?

**Comment by AleksandarMiha** [comment]
@Marcelh1983

**Comment by Marcelh1983** [comment]
Hi @AleksandarMiha , if you use the google or office viewer then it's impossible because the content is rendered in an iframe.

**Comment by AleksandarMiha** [comment]
No I am using mammoth

    <ngx-doc-viewe```
r   [url]="doc" class="center-law" viewer="mammoth" style="width:100%;height:93vh;"> 
    </ngx-doc-viewer
```>

@Marcelh1983

**Comment by Marcelh1983** [comment]
It should be possible, I don't know what would be the best way to do this. But I is possible to search words and wrap these in a span with a highlight class.

**Comment by AleksandarMiha** [comment]
When I using any Pipe it is no work..maybe is my mistake. Can you hint me how to do it ?

**Comment by AleksandarMiha** [comment]
@Marcelh1983

**Comment by AleksandarMiha** [comment]
I am try to set pipe direct in ngx-doc-viewer tag but no work..where should be pipe ?

**Comment by AleksandarMiha** [comment]
Search pipe get any array and search in array. Here i don't have array i have only doc link..

**Comment by Marcelh1983** [comment]
I created an [example](https://github.com/Marcelh1983/mammoth-highlight)

**Comment by Marcelh1983** [comment]
I updated the example by creating a component with the highlight behavior. Now it's easy for you to copy that component from my example if you want to.

Good luck!

**Comment by AleksandarMiha** [comment]
This is nice. I will try to insert in my project. Thank you Marcelh

**Comment by abhishekssrao** [comment]
Can you please share the code and snapshots, I am also getting the same issue for many days, it will be very helpful
