### ISSUE TITLE
Base64 values

### ISSUE THREAD

**Issue by tjvg91** [Marcelh1983/angular-document-viewer#49]
Does this access base64 value for url?

**Comment by Marcelh1983** [comment]
Hi @tjvg91 the google and office viewer will only work with a document that is publicly available. The mammoth viewer does support local docx files. I think it now works with a path to the resource only. I you want to use this, I'll will create a new version that supports base64 documents.

**Comment by Sathishchary** [comment]
Hi @Marcelh1983 , We have same requirement, docx blob is coming from the server.. but the blob is not supporting, this plugin is working with only public urls, we tried to convert docx blob to base64 url, but that is not working...
any suggestionss..
 
thanks

**Comment by Marcelh1983** [comment]
Hi @Sathishchary,
The mammoth viewer will support base64, but it renders not as good as the Google or office viewer. In my projects I use the office viewer and have my documents hosted in azure blobstorage.

**Comment by Sathishchary** [comment]
Thanks for the info @Marcelh1983, may i know the details and links about office viewer.. how can i show docx blob in office viewer.
i will check the mammoth viewer also.

**Comment by Marcelh1983** [comment]
You cann't show docx blobs in the office viewer. Azure blob storage provides you with an url to the docx file

**Comment by Sathishchary** [comment]
Thanks for the info @Marcelh1983.

**Comment by Tthienphuc147** [comment]
Hi @Marcelh1983 ,We have problem with view file pdf, in macOS environment.we can't download file pdf
Thanks

**Comment by ammad172** [comment]
> Hi @Sathishchary, The mammoth viewer will support base64, but it renders not as good as the Google or office viewer. In my projects I use the office viewer and have my documents hosted in azure blob storage.

Hi Marchell can you share your code snippet how we can actually preview docx base64 using this library.
I have tried myself but was unsuccessful. It will be very helpful if i got the code snippet for how can we preview base64 docx data
