### ISSUE TITLE
"NO PREVIEW AVAILABLE."

### ISSUE THREAD

**Issue by ShashankM3-hexaware** [Marcelh1983/angular-document-viewer#5]
<ngx-doc-viewer [url]= "imageSrc" viewer="google" style="width:100%;height:75vh;"></ngx-doc-viewer>
imageSrc : https://172.25.141.122:3001/api/uploads/40084/Sachin Vibhute_Jan_Week 1.pdf

I'am facing NO PREVIEW AVAILABLEn error. any idea about it?

**Comment by Marcelh1983** [comment]
Hi,
The file must be publicly accessible to be served by the google view.  https://172.25.141.122:3001/ won't be accessible
