### ISSUE TITLE
Google viewer

### ISSUE THREAD

**Issue by JojiePalahang** [Marcelh1983/angular-document-viewer#50]
Hi just want to confirm when I want to use google viewer files need to be hosted in google drive?

**Comment by Marcelh1983** [comment]
Hi @JojiePalahang. To view a document in de google viewer it should be public available. Don't have to be hosted in google drive.

**Comment by JojiePalahang** [comment]
Hi @Marcelh1983  does url viewer support tiff?

**Comment by Marcelh1983** [comment]
url viewer just shows an url in the browser. So if the browser supports displaying tiff files; yes, otherwise no.
