### ISSUE TITLE
Theme in docx files is not respected

### ISSUE THREAD

**Issue by lud42** [Marcelh1983/angular-document-viewer#57]
I'm uploading a docx file with the viewer "mammoth" who contains multiple tables and with some colors but all the style is not appears when it's displayed

**Comment by Marcelh1983** [comment]
Hi @lud42, the mammoth viewer uses [mammoth ](https://github.com/mwilliamson/mammoth.js) to convert the document into html. It's conversion does not cover all options word has, see mammoth github. If you still want to file an issue regarding to the conversion you should do it on mammoth github.
