### ISSUE TITLE
Error with local file

### ISSUE THREAD

**Issue by Kehylaicaza** [Marcelh1983/angular-document-viewer#58]
I need to read a file that is saved in localhost of the server, but it presents me with this error
"Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist."
and don't read it

por favor ayuda, Thank you
`<ngx-doc-viewer 
viewerUrl="https://docs.google.com/gview?url=%URL%&embedded=true"
url="http://localhost:3000/uploads/fhQlcejbN9mQm1ZRlq9sKV_a.docx"
viewer="url" style="width:100%;height:50vh;">
</ngx-doc-viewer>`

**Comment by Marcelh1983** [comment]
Hi @Kehylaicaza, the viewer: https://docs.google.com/gview?url=%URL%&embedded=true won't be able to find the document since it is hosted on your localhost. It probably works if you host your application on a public domain and the docx is publicly available.
