### ISSUE TITLE
ngcc failed after installation only

### ISSUE THREAD

**Issue by archoudhury** [Marcelh1983/angular-document-viewer#59]
After installation ngcc failed (error attached).
But when I disabled ivy compiler ("enableIvy": false,) it went through. (This is not the proper way).

i am using angular 9
"@angular/cli": "^9.1.0",
"@angular/compiler-cli": "~9.0.2",

![image](https://user-images.githubusercontent.com/58773939/90336242-0c54f800-dff8-11ea-83c4-90d8360aacc5.png)

Please feel free to ask me if any further information needed.

**Comment by Marcelh1983** [comment]
are you targetting es5?

**Comment by PhathiS** [comment]
Hi Marcelh1983, I also have the same issue and yes in my case I am targeting es5.

Is there a way around this issue?

**Comment by Marcelh1983** [comment]
Could you try:

"So in order to project with "target": "es5" work, after using npm install you have to run ngcc.

You can add it in your package.json file:

{
  "scripts": {
    "postinstall": "ngcc"
  }
}
"
https://stackoverflow.com/a/63727427/6729295
