### ISSUE TITLE
Unable to open blob url created using createObjectURL

### ISSUE THREAD

**Issue by Sasi2491** [Marcelh1983/angular-document-viewer#6]
I am not able to open the files from blob URL like this: blob:http://localhost:4200/84881c34-fcdc-43ca-a92a-b4be9ea6a89c

Is there any way to open files created from blob?

**Comment by Marcelh1983** [comment]
Hi @Sasi2491 the url should be public available. So localhost won't work. Also url's from a blob seems not to work in the google and office viewer. Isn't there another way you could deal with those files?
