### ISSUE TITLE
disableContent not working

### ISSUE THREAD

**Issue by srikarkonda** [Marcelh1983/angular-document-viewer#61]
disableContent is only working for option "all".It not working in other options. please resolve the issue.

**Comment by Marcelh1983** [comment]
don't know what you'd except. Are the other options not doing as the documentation describes?

**Comment by srikarkonda** [comment]
disableContent not working as per documentation description.

**Comment by Marcelh1983** [comment]
I have no time to look into this issue. If you'd provide a very specific description of the problem I'll might re-open it and try to fix it. Also feel free to clone the repo, fix the issue (I'd like to collaborate if you get stuck) and do a pull request
