### ISSUE TITLE
Demo snippet on npmjs.com not working.

### ISSUE THREAD

**Issue by Bernold1** [Marcelh1983/angular-document-viewer#62]
The snippet found on https://www.npmjs.com/package/ngx-doc-viewer for google drive viewer does not work correctly and only displays embedded html. When using the same url inside of the demo (_https://angular-doc-viewer.firebaseapp.com/_) you achieve the same results. 
```
    <ngx-doc-viewer
        [url]="http://docs.google.com/fileview?id=0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh"
        viewer="url" style="width:100%;height:50vh;">
    </ngx-doc-viewer>
```

**Comment by Bernold1** [comment]
Also in the documentation it is not clear if using the google viewer only supports URL's directly linked to google drive. Can you use any url with the google viewer?

**Comment by Marcelh1983** [comment]
@Bernold1 thanks for reporting!
