### ISSUE TITLE
Application not loading in IE Browser after installing ngx-doc-viewer

### ISSUE THREAD

**Issue by Santhosh-VS-M** [Marcelh1983/angular-document-viewer#63]
After installing ngx-doc-viewer, Application is not loading in IE browser. After uninstalling ngx-doc-viewer, It is working fine in IE browser. But I need document viewer and should work in IE browser also.
Uncommented required lines in polyfills.ts
In Console, it is showing error at "Class" keyword.
![image](https://user-images.githubusercontent.com/73743190/97779202-96960c80-1ba2-11eb-88a5-02a67d53cbd7.png)
![image](https://user-images.githubusercontent.com/73743190/97779244-c9400500-1ba2-11eb-98c2-7da492a78136.png)

My tsconfig.ts 
![image](https://user-images.githubusercontent.com/73743190/97779295-1cb25300-1ba3-11eb-930c-c8c52fae41f6.png)

Using @angular/cli : 7.0.4

polyfills.ts : 
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/guide/browser-support
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'core-js/es6/array';
import 'core-js/es7/array';
import 'hammerjs';

/**
 * If the application will be indexed by Google Search, the following is required.
 * Googlebot uses a renderer based on Chrome 41.
 * https://developers.google.com/search/docs/guides/rendering
 **/
 import 'core-js/es6/array';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';

/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 **/
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

  //(window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
  //(window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
  //(window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
 (window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.

//import * as svg4everybody from 'svg4everybody';
//svg4everybody({ polyfill: true });

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

**Comment by Marcelh1983** [comment]
Hi @Santhosh-VS-M,

I opened https://angular-doc-viewer.firebaseapp.com/ in Internet Explorer and the page shows. Could you confirm the demo sites works in Internet Explorer on your pc as well. If so, you maybe find something in the differences between the demo application and your application

**Comment by Marcelh1983** [comment]
Is this the same issue as #59?

**Comment by gopikrishnas** [comment]
Hi @Marcelh1983 , I too got the same issue in IE7.
my app is not compiling the ngx-doc-viewer code to ES5 version I think. It is showing as class for my 
I checked your demo url in IE11 and it is working file. But seem the demo page is using Angular 10 version. But my app is using Angular version 7.0.0. So I cannot use "ngcc" as mentioned in #59 

Below is my package.json file

>{
>   "name": "tech",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^7.0.4",
>     "@angular/common": "~7.0.0",
>     "@angular/compiler": "~7.0.0",
>     "@angular/core": "~7.0.0",
>     "@angular/forms": "~7.0.0",
>     "@angular/http": "~7.0.0",
>     "@angular/platform-browser": "~7.0.0",
>     "@angular/platform-browser-dynamic": "~7.0.0",
>     "@angular/router": "~7.0.0",
>     "@ng-bootstrap/ng-bootstrap": "^4.1.2",
>     "angular-datatables": "^7.0.0",
>     "angular2-cookie": "^1.2.6",
>     "classlist.js": "^1.1.20150312",
>     "core-js": "^2.5.4",
>     "cross-storage": "^1.0.0",
>     "datatables.net": "^1.10.19",
>     "datatables.net-buttons": "^1.6.2",
>     "datatables.net-buttons-dt": "^1.6.2",
>     "datatables.net-colreorder": "^1.5.2",
>     "datatables.net-colreorder-dt": "^1.5.2",
>     "datatables.net-dt": "^1.10.19",
>     "datatables.net-responsive": "^2.2.3",
>     "datatables.net-responsive-dt": "^2.2.3",
>     "datatables.net-select": "^1.3.1",
>     "datatables.net-select-dt": "^1.3.1",
>     "dateformat": "^3.0.3",
>     "file-saver": "^2.0.2",
>     "hammerjs": "^2.0.8",
>     "jszip": "^3.5.0",
>     "mammoth": "^1.4.9",
>     "moment": "^2.24.0",
>     "ng-multiselect-dropdown": "0.2.3",
>     "ng2-file-upload": "^1.3.0",
>     "ngx-bootstrap": "^4.2.0",
>     "ngx-bootstrap-multiselect-dropdown": "^1.0.10",
>     "ngx-doc-viewer": "^1.3.0",
>     "ngx-loading": "^3.0.1",
>     "ngx-toastr": "^10.0.4",
>     "pdfmake": "^0.1.68",
>     "rxjs": "~6.3.3",
>     "rxjs-compat": "^6.5.2",
>     "safe-pipe": "^1.0.3",
>     "svg4everybody": "^2.1.9",
>     "tiff.js": "^1.0.0",
>     "web-animations-js": "^2.3.2",
>     "zone.js": "~0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.13.9",
>     "@angular/cli": "~7.0.4",
>     "@angular/compiler-cli": "^7.2.15",
>     "@angular/language-service": "~7.0.0",
>     "@types/datatables.net": "^1.10.17",
>     "@types/datatables.net-buttons": "^1.4.3",
>     "@types/datatables.net-select": "^1.2.6",
>     "@types/jasmine": "~2.8.8",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/jquery": "^3.3.29",
>     "@types/node": "~8.9.4",
>     "codelyzer": "~4.5.0",
>     "jasmine-core": "~2.99.1",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~3.0.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "~1.1.2",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.11.0",
>     "typescript": "~3.1.1"
>   },
>   "browser": {
>     "fs": false,
>     "path": false,
>     "os": false,
>     "crypto": false
>   }
> }

below is my tsconfig.json

> {
>   "compileOnSave": false,
>   "compilerOptions": {
>     "baseUrl": "./",
>     "outDir": "./dist/out-tsc",
>     "sourceMap": true,
>     "declaration": false,
>     "module": "es2015",
>     "moduleResolution": "node",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "target": "es5",
>     "paths": {
>       "crypto": [
>         "node_modules/crypto-js"
>       ]
>     },
>     "typeRoots": [
>       "node_modules/@types"
>     ],
>     "lib": [
>       "es2018",
>       "dom"
>     ]
>   }
> }

and below is my polyfills.ts


> /***************************************************************************************************
>  * BROWSER POLYFILLS
>  */
> 
> /** IE9, IE10 and IE11 requires all of the following polyfills. **/
> import 'core-js/es6/symbol';
> import 'core-js/es6/object';
> import 'core-js/es6/function';
> import 'core-js/es6/parse-int';
> import 'core-js/es6/parse-float';
> import 'core-js/es6/number';
> import 'core-js/es6/math';
> import 'core-js/es6/string';
> import 'core-js/es6/date';
> import 'core-js/es6/regexp';
> import 'core-js/es6/map';
> import 'core-js/es6/weak-map';
> import 'core-js/es6/set';
> 
> /**
>  * If the application will be indexed by Google Search, the following is required.
>  * Googlebot uses a renderer based on Chrome 41.
>  * https://developers.google.com/search/docs/guides/rendering
>  **/
> import 'core-js/es7/array';
> 
> /** IE10 and IE11 requires the following for NgClass support on SVG elements */
> import 'classlist.js';  // Run `npm install --save classlist.js`.
> 
> /** IE10 and IE11 requires the following for the Reflect API. */
> import 'core-js/es6/reflect';
> 
> /**
>  * Web Animations `@angular/platform-browser/animations`
>  * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
>  * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
>  **/
> import 'web-animations-js';  // Run `npm install --save web-animations-js`.
> 
> /**
>  * By default, zone.js will patch all possible macroTask and DomEvents
>  * user can disable parts of macroTask/DomEvents patch by setting following flags
>  */
> 
> //(window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
> //(window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
> //(window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
> 
> /*
> * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
> * with the following flag, it will bypass `zone.js` patch for IE/Edge
> */
> (window as any).__Zone_enable_cross_context_check = true;
> 
> /***************************************************************************************************
>  * Zone JS is required by default for Angular itself.
>  */
> import 'zone.js/dist/zone';  // Included with Angular CLI.
> 
> import * as svg4everybody from 'svg4everybody';
> svg4everybody({ polyfill: true });
> 
> /***************************************************************************************************
>  * APPLICATION IMPORTS
>  */
> import 'hammerjs/hammer';
> 

Does 1.3.0 works with Angular 7.0.0?

**Comment by Marcelh1983** [comment]
It does not work.  You could use version 0.1.19: `npm i ngx-doc-viewer@0.1.19` that one would probably work
