### ISSUE TITLE
Authorized view doc

### ISSUE THREAD

**Issue by hayat12** [Marcelh1983/angular-document-viewer#64]
cant pass header to view the protected files

**Comment by sgomez84** [comment]
@Marcelh1983 @hayat12 This would be a great addition to the magnificent package. Any leads how we can do this?

**Comment by sgomez84** [comment]
[WebODF](https://webodf.org/about/features.html )

**Comment by Marcelh1983** [comment]
Hi @sgomez84 and @sgomez84,
you mean access files that have permissions, not available for everyone? The Google and office 365 viewers won't allow something like that. With azure blobstorage you can make documents available for like 10 minutes with a sas token, but it still be public available for that time. Suggestions, pull requests are very welcome.
