### ISSUE TITLE
Error using office viewer

### ISSUE THREAD

**Issue by SureshKumar-Java** [Marcelh1983/angular-document-viewer#68]
Hello,

I am trying office viewer to preview .docx files. But I am getting below error.
My document is on server.

If I can't use google/office viewer for documents on server which viewer is suggestable. Please suggest.

![image](https://user-images.githubusercontent.com/76013307/103673878-139b8480-4f4c-11eb-863e-41b2e7e6aa7f.png)

**Comment by Marcelh1983** [comment]
This seems to be a problem with the document you want to view. Is it publicly available? Is the url correct?
