### ISSUE TITLE
Google Viewer doesn't always load file

### ISSUE THREAD

**Issue by flutteresbolivia** [Marcelh1983/angular-document-viewer#70]
When using the Google viewer to try and load a file, it doesn't always render the file first time or after a few tries. Whats confusing is that the loaded event is emitted from the doc viewer even though I still can't see the document.

`    <ngx-doc-viewer [url]="pdfSrc" viewer="google" style="width:100%;height:50vh;"></ngx-doc-viewer>
`

**Comment by nikhil1414** [comment]
hello, I am facing the same issue , have you found the solution??

**Comment by Marcelh1983** [comment]
Hi @nikhil1414 @flutteresbolivia  I haven't found a solution. You can play with the googleCheckContentLoaded and googleCheckInterval properties. Can you create a stackblitz where I can reproduce the problem?

**Comment by Marcelh1983** [comment]
Something the Google viewer doesn't show the document. In the 2.0x version I think i solved that problem. It's going to be loaded eventually. I do a reload for the cases where it doesn't show up but that takes some loading time.
