### ISSUE TITLE
Error using google viewer

### ISSUE THREAD

**Issue by CheyneSantana** [Marcelh1983/angular-document-viewer#71]
When I try to preview txt or xlsx files, the google viewer do not preview the files
Trying preview the txt file, return this:
![image](https://user-images.githubusercontent.com/13357739/104671283-410acf80-56bc-11eb-976e-fc39673e855a.png)
![image](https://user-images.githubusercontent.com/13357739/104671372-6f88aa80-56bc-11eb-97ec-8e374fe71bc6.png)

Trying preview the xlsx file, freeze on reloading
![image](https://user-images.githubusercontent.com/13357739/104671465-a9f24780-56bc-11eb-8051-c7bc1417506c.png)

**Comment by Marcelh1983** [comment]
Hi @CheyneSantana , is the file publicly available? I tested a txt file in the [demo app ](https://angular-doc-viewer.web.app/) If i past this url: https://www.le.ac.uk/oerresources/bdra/html/resources/example.txt it seems to work.
