### ISSUE TITLE
Does not show office ppt docs

### ISSUE THREAD

**Issue by Nathan187** [Marcelh1983/angular-document-viewer#74]
Maybe I'm doing something wrong. It's not showing the ppt file from the assets directory.  now sure why this is

is this working for anyone else?

**Comment by revl94** [comment]
I have the same problem but with docx file, only appear an message: 'An error occurred'. Plis help

**Comment by Nathan187** [comment]
starting to think , this is no longer supported

**Comment by Marcelh1983** [comment]
I try to help if I have some time off. A ppt file from the asset folder does work in the example app. Note that it doesn't work from localhost because then your assets is not publicly available. Let me know if I can further assist you

**Comment by revl94** [comment]
its okay, thanks you!!

**Comment by Nathan187** [comment]
thank you for responding.  i was able to get this to work.  i had to place the document in a location that's accessible via https.

is there anyway to remove the option to download?
thank you

![Screen Shot 2021-03-18 at 4 25 51 PM](https://user-images.githubusercontent.com/1022238/111701352-b43dd880-8808-11eb-815c-78165d684275.png)

**Comment by Marcelh1983** [comment]
Good to hear you solved the problem. The download button is part of the office viewer and I don't have any influence on that. What I already did for the Google viewer is adding the possibility to try to render a div on top of the toolbar,e.g. A black div on top of the toolbar positioned absolute. That way the button isn't visible. You can try to do that.
