### ISSUE TITLE
Can the url of the document be replaced by byte array.

### ISSUE THREAD

**Issue by manojmaity** [Marcelh1983/angular-document-viewer#8]
Hi there,
         We have got a webapi, which return file content as byte array. Using angular application we have  to showcase a preview of the document to the user.
         Can the url of the document, be replaced by byte array.

Thanks in advance.

**Comment by Marcelh1983** [comment]
Hi @manojmaity this is just a wrapper for the google and office document viewer with only supports url's. The only ways is to serve the document somewhere e.g. use something like Azure blob storage.

**Comment by Marcelh1983** [comment]
Hi @manojmaity maybe you don't need it anymore but `npm i ngx-doc-viewer@next` will have the mammoth viewer. Which converts docx to html locally. If you use createObjectURL() from your byte array if will work.

Also add mammoth: 
```sh
npm install mammoth --save
```
and make sure mammoth.browser.min.js is loaded. For the angular/cli you would add the following in angular.json:

```json
    "scripts": [
        "node_modules/mammoth/mammoth.browser.min.js"
    ]
```
See the demo site in local-files branch for example code.

**Comment by manojmaity** [comment]
First of all thanks for replying, with such cutting edge solution.
I will definitely give it a try.
